name: counter
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.7.0
  injectable: ^2.4.4
  auto_route: ^8.3.0

  flutter_bloc: ^8.1.6

  package_info_plus: ^8.0.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^8.1.0
  injectable_generator: ^2.6.2

  build_runner:

  flutter_lints: ^3.0.0
  custom_lint: ^0.6.4

flutter:
  uses-material-design: true
